In [1]:
import numpy as np

In [2]:
lis = [1,2,3,4,5]
arr = np.array(lis)

In [4]:
type(arr)

numpy.ndarray

In [10]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [16]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l3 = [11,12,13,14,15]
arr = np.array([l1 , l2 , l3])

In [17]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
arr.shape

(3, 5)

In [23]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [24]:
arr.shape

(3, 5)

In [31]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [34]:
arr[1:,2:4]

arr[1,1:4]

array([7, 8, 9])

In [37]:
arr = np.arange( 0 , 10 , 2)
arr

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(1 , 10 , 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [41]:
arr[3:] = 100

In [42]:
arr

array([  0,   2,   4, 100, 100])

In [43]:
arr1 = arr

In [44]:
arr

array([  0,   2,   4, 100, 100])

In [45]:
arr1[3:] = 500

In [46]:
arr1

array([  0,   2,   4, 500, 500])

In [47]:
arr

array([  0,   2,   4, 500, 500])

In [48]:
arr2 = arr.copy()

In [49]:
print(arr)
arr2[3:] = 1000
print(arr2)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [52]:
# exploratory data anal

var = 2
arr[arr < 10]

array([0, 2, 4])

In [55]:
np.ones(5 , dtype=int)

array([1, 1, 1, 1, 1])

In [59]:
np.random.rand(5 , 5)

array([[0.7322345 , 0.58669176, 0.60889751, 0.21399115, 0.37322841],
       [0.37772391, 0.50250421, 0.77439283, 0.11907873, 0.23722223],
       [0.20184587, 0.40517163, 0.71497326, 0.13695534, 0.44381917],
       [0.10444708, 0.78253045, 0.39551683, 0.55963076, 0.45768917],
       [0.44996319, 0.2852749 , 0.79916076, 0.61604463, 0.38473473]])

In [60]:
np.random.randn(5 , 5)

array([[-0.17543204,  0.27666468, -0.42539959,  0.06003851,  1.56302251],
       [ 0.37239816, -0.9362482 ,  0.35770288, -0.67094306,  0.88745958],
       [-0.57085635,  1.82111951, -2.4150652 ,  1.54618871, -0.90290959],
       [ 0.86427507, -0.42716575,  0.27594706, -1.17109983, -0.52644131],
       [-0.83044511, -1.69478092, -0.51707177,  0.5777619 ,  0.97441553]])

In [67]:
np.random.randint(5 , 50 , 10).reshape(2,5)

array([[10, 48, 20, 13, 29],
       [23, 37, 42,  6, 32]])